teste = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(teste)}')
print(f'Só tem espaços? {teste.isspace()}')
print(f'É um número? {teste.isnumeric()}')
print(f'É alfabético? {teste.isalpha()}')
print(f'É alfanumérico? {teste.isalnum()}')
print(f'Está em maiúsculas? {teste.isupper()}')
print(f'Está em minúsculas? {teste.islower()}')
print(f'Está capitalizada? {teste.istitle()}')